### ISSUE TITLE
Homebrew fails on builds because of being removed from Ubuntu runners

### ISSUE THREAD

**Issue by mrlesmithjr** [mrlesmithjr/dockerfiles#44]
Reference - https://github.com/actions/runner-images/issues/6283 and https://github.com/Homebrew/actions/tree/master/setup-homebrew

```yaml
- name: Set up Homebrew
  id: set-up-homebrew
  uses: Homebrew/actions/setup-homebrew@master
```
